name: Weekly Architecture Audit

on:
  schedule:
    - cron: "0 6 * * 6"  # Every Saturday at 06:00 UTC
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  architecture-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jinja2

      - name: Run architecture audit
        env:
          OPENHANDS_API_KEY: ${{ secrets.OPENHANDS_API_KEY }}
        run: |
          cd scripts
          python cron_agents.py architecture-audit \
            --api-key "$OPENHANDS_API_KEY" \
            --repository "${{ github.repository }}" \
            --branch "main" \
            --output ../architecture_audit_result.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: architecture-audit-results
          path: architecture_audit_result.json
