name: Weekly Architecture Audit

on:
  schedule:
    - cron: "0 6 * * 6"  # Every Saturday at 06:00 UTC
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: ''

permissions:
  contents: read
  issues: write

jobs:
  architecture-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jinja2

      - name: Run architecture audit
        env:
          CRON_AGENTS_ISSUE_NUMBER: "97"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          OPENHANDS_API_KEY: ${{ secrets.OPENHANDS_API_KEY }}
        working-directory: scripts
        run: |
          python cron_agents.py architecture-audit \
            --repository "${{ github.repository }}" \
            --branch "main"
